# AntiShare Configuration:
# Events:
#   'block_place' - Blocks/items to deny for block placing
#   'block_break' - Blocks/items to deny for block breaking
#   'death' - Blocks/items to not allow to drop on death
#   'drop_item' - Block/items to not allow to drop when a player presses (default) Q
#   'interact' - Blocks/items to deny interactions to. (Left/Right click)
#   'commands' - Commands to block, define a new command with a SPACE (defaults block '/somecommand' and '/anothercommand')
#   -- Want all blocks/items to be denied? Put a *
#   -- Want no blocks/items to be denied? Put: none
#   -- Make sure item lists are space-seperated, not commas, periods, or fancy other things!
# 
# Messages:
#   All messages are when they are declined an action.
#   Chat colors are supported using the & sign (eg: &f = white)
#   If you wouldn't like a message to show, set the value as 'noshow'
# 
# Other:
#   'only_if_creative' - Auto-decline if they are in creative, permissions still apply.
#     (eg: A player doesn't have the allow or decline permission to place, and is in creative, places a block: declined)
#       For per-player support, set the permission "AntiShare.onlyIfCreative". See the permissions section for more information
#   'allow_eggs' - If false then eggs cannot be used (the ones that spawn mobs, like creepers)
#   'inventory_swap' - If true then creative and survival inventories will be swapped
#   'track_blocks' - If true then creative mode blocks will be tracked where only creative mode players can break them
#              (unless they have the permission "AntiShare.blockBypass")  
#   'allow_bedrock' - If false then bedrock will never be broken or placed
#   'pvp' - True if you want to allow creative players to hit other players ("AntiShare.pvp" to allow to specific players)
#   'pvp-mobs' - True if you want to allow creative players to be able to hit mobs ("AntiShare.mobpvp" to allow to specific players)
#   'blockDrops' - Only works if 'track_blocks' is in effect. If true, you allow allow the creative-mode block to be broken, but no drops will be produced
#                  If false, you don't allow the block to be broken (1.0.6 and prior default). While breaking (if this is true) AntiShare sends the message
#                  'noBlockDrop' to the player once per second, or for every different block. As well, when the block is 100% broken it will show 'creativeModeBlock'.
#   'worldTransfer' - True if you would like to allow players to transfer worlds. See the section towards the end of this documentation labeled "world transfer information" for help.
#                     True means you can transfer TO the world, false means you cannot.
#   'tracked-blocks' - The blocks the plugin should track and mark as "creative" blocks (if the player placing is in creative). This list is SPACE defined (see default)
#                    You can set this to 'none' or '*' as well if you prefer, 'none' meaning don't track (set 'track_blocks' to false to reduce some possible lag), '*' meaning
#                    track everything placed.
# 
#   The following are affected by 'only_if_creative': 'allow_eggs', 'allow_bedrock', 'pvp', 'pvp-mobs', 'worldTransfer', and all the 'events'
#   This means the above settings will check if they are in creative or not and act upon that
# Settings:
#   'save-interval' - This is the interval, in minutes, you want AntiShare to save it's data to disk (default is 30 minutes)
# SQL:
#   'use' - If this is false, flat-file storage will be used instead
#   'host' - The SQL host, usually localhost
#   'username' - The SQL username to use, this user must be able to create/edit/view tables in the database
#   'password' - The SQL password for the above username
#   'port' - The SQL port, this is unused thus far (will be used in later support)
#   'database' - The SQL database to use, this must already be made
# 
# Notifications:
#   - Used to alert specific people of actions taking place
#   'send' - True to send notifications, false otherwise
#   'illegal' - All the illegal (blocked) actions, the name of the action relates to the action (eg: block_place means an illegal block was placed)
#   'legal' - All the legal (allowed) actions, the name of the action relates to the action (eg: block_place means an legal block was placed)
#   'general' - Everything else that doesn't fit into a category (illegal/legal)
#             - Note: region_enter/exit is affected by a region's 'Show Message' property, you can read about these messages a bit further down
#  
# Permissions:
#   'AntiShare.allow.*' - Allow all events
#   'AntiShare.allow.place' - Allow block placing
#   'AntiShare.allow.break' - Allow block breaking
#   'AntiShare.allow.death' - Allow item drops on death
#   'AntiShare.allow.drop' - Allow item dropping
#   'AntiShare.allow.interact' - Allow interactions
#   'AntiShare.allow.eggs' - Allow eggs that spawn mobs
#   'AntiShare.allow.commands' - Allow command usage (for specified commands)
#   ** If you would like to deny an event, set the node to false (default is false)
#   ** By default, AntiShare assumes "Deny" on all creative mode players (or all players if 'onlyIfCreative' is set to false)
#   'AntiShare.onlyIfCreative' - Only deny actions if the player is in creative mode, false to deny regardless of Game Mode (this is default FALSE)
#   'AntiShare.onlyIfCreative.global' - Uses the configuration value and overrides the 'AntiShare.onlyIfCreative' permission (this is default TRUE)
#   'AntiShare.reload' - Permission to use /antishare reload
#   'AntiShare.regions' - Permission to set/remove GameMode Regions
#   'AntiShare.roam' - If set as true, the target can roam through regions without having their gamemode change
#   'AntiShare.noswap' - If true, the player is exempt from inventory swapping, otherwise they will have their inventory switched
#   'AntiShare.blockBypass' - If true, then the player can bypass the "Creative mode players can only break this block" message
#                           - As well they can break a block and get drops if 'blockDrops' (under 'other') is true
#   'AntiShare.freePlace' - If true, then the player can place a "creative-mode" block without it being registered as a "creative-mode" block
#   'AntiShare.bedrock' - If true, then the player can break and place bedrock
#   'AntiShare.pvp' - Allows PVP to a creative mode player
#   'AntiShare.mobpvp' - Allows Mob PVP to a creative mode player
#   'AntiShare.worlds' - Allows world teleporting without being blocked, also stops multi-world inventories for the target
#   'AntiShare.notify' - Sends notifications to the player
#   'AntiShare.silent' - Stops the sending of notifications from this player
#   'AntiShare.admin' - Includes "AntiShare.allow.*", "AntiShare.reload", "AntiShare.regions", "AntiShare.roam", "AntiShare.blockBypass", 
#                         "AntiShare.freePlace", "AntiShare.bedrock", "AntiShare.pvp", "AntiShare.worlds", "AntiShare.notify", "AntiShare.silent", 
#                         and "AntiShare.mobpvp".
# 
# Commands:
#   '/antishare'
#     Aliases: '/as', '/antis', '/ashare'
#   '/as help' - Displays command usage
#   '/as reload' - Reloads configuration
#   '/as region <gamemode> <name>' - Sets your currently selected WorldEdit region as a GameMode Region and names the region
#   '/as rmregion' - Removes the GameMode region you are in
#   '/as rmregion <name>' - Removes a region by name (console friendly)
#   '/as editregion <name> <key> <value>' - Set various properties of a region, see below for help
#   '/as listregions' - List the regions available
#   '/as listregions #' - List the regions by page
# 
# Notes:
#   - Permissions default to all deny as true while all allow as OP or higher.
#   - 'only_if_creative' will override the permissions meaning if a player is in survival-mode while 'only_if_creative' is true then 
#     the deny permissions will be ignored (eg: That survival player places a block: it is placed)
#   - The default settings decline interactions with furnaces, chests, dispensers, and chest-minecarts
#   - The event 'block_break' is set to 'none' because in creative-mode, no blocks are dropped when broken
#   - Messages support colors, use '&' to define a color. Eg: "&aWelcome!" will display "Welcome!" in green.
#   - By default, the 'onlyIfCreative' permissions mirror the default configuration (to avoid breaking)
# 
# World Transfer Help:
#   Here is a table of values to show you what would happen depending on settings:
#   If a world manager is detected (like Multiverse), AnitShare will not do anything to avoid conflict (regardless of settings)
#   ------------------------------------------------------------------------------
#   | worldTransfers | only_if_creative |                  Result                |
#   ------------------------------------------------------------------------------
#   |      true      |       true       | All players can transfer worlds        |
#   ------------------------------------------------------------------------------
#   |      true      |       false      | All players can transfer worlds        |
#   ------------------------------------------------------------------------------
#   |      false     |       true       | Only creative mode players are blocked |
#   ------------------------------------------------------------------------------
#   |      false     |       false      | All players are blocked from transfers |
#   ------------------------------------------------------------------------------
#
# WHAT IS A GAMEMODE REGION?
#   A GameMode region is a WorldEdit region where a player automatically changes GameModes. Upon leaving their GameMode is restored.
#   All the same functions apply, such as inventory changes, blocks, etc. You can configure the region to have properties like a
#   a specific inventory to be given to the player upon entry, or to let the player know when they enter/leave the area. All of the 
#   options are configurable in-game using /as editregion. Type /as editregion <region name> <key> <value> to set a property.
#   
#   KEYS AND VALUES (with explanations):
#   Note: Keys are case in-sensitive
#   -------------------------------------------------------------------------------------------------------------
#   | KEY              | POSSIBLE VALUES      | DESCRIPTION                                                     |
#   -------------------------------------------------------------------------------------------------------------
#   | name             | <a name>             | Sets the name of the region                                     |
#   -------------------------------------------------------------------------------------------------------------
#   | ShowEnterMessage | true/false           | Set to true to enable the 'onEnter message'                     |
#   -------------------------------------------------------------------------------------------------------------
#   | ShowExitMessage  | true/false           | Set to true to enable the 'onExit message'                      |
#   -------------------------------------------------------------------------------------------------------------
#   |                  |                      | Sets the region's inventory; 'none' to stop the changing        |
#   | inventory        | 'none'/'set'         | of inventories, 'set' to set the region's inventory to          |
#   |                  |                      | mirror yours. 'set' cannot be done from console, 'none' can.    |
#   -------------------------------------------------------------------------------------------------------------
#   | gamemode         | 'creative'/'surival' | Sets the gamemode of the region                                 |
#   -------------------------------------------------------------------------------------------------------------
#   | area             | No Value             | No value required; Sets the area of the region to your current  |
#   |                  |                      | WorldEdit selection.                                            |
#   -------------------------------------------------------------------------------------------------------------
events:
  block_break: none
  block_place: 57 41 42
  death: '*'
  drop_item: '*'
  interact: 23 61 62 54 342
  commands: '/somecommand /anothercommand'
messages:
  block_break: You can't do that!
  block_place: You can't do that!
  death: You can't do that!
  drop_item: You can't do that!
  interact: You can't do that!
  eggs: You can't use the spawn eggs!
  inventory_swap: Your inventory has been changed.
  creativeModeBlock: You cannot break that block! It was placed by a creative mode player.
  bedrock: You cannot play with bedrock!
  pvp: You cannot hit other players!
  mobpvp: You cannot hit mobs!
  noBlockDrop: You will not get anything from breaking that!
  illegalCommand: You cannot use that command!
  worldSwap: You cannot transfer to that world!
other:
  only_if_creative: true
  allow_eggs: false
  inventory_swap: true
  track_blocks: true
  allow_bedrock: false
  pvp: false
  pvp-mobs: false
  blockDrops: false
  worldTransfer: false
  tracked-blocks: '*'
SQL:
  use: false
  host: localhost
  username: AntiShare
  password: AntiSharePW
  port: 3306
  database: AntiShare
settings:
  save-interval: 30
notifications:
  send: true
  illegal:
    block_place: true
    block_break: true
    death: true
    drop_item: true
    interact: true
    command: true
    egg: true
    creative_block_break: true
    pvp: true
    mob-pvp: true
    bedrock_attempt: true
    world_transfer: true
  legal:
    block_place: false
    block_break: false
    death: false
    drop_item: false
    interact: false
    command: false
    egg: false
    creative_block_break: false
    pvp: false
    mob-pvp: false
    bedrock_attempt: false
    world_transfer: false
  general:
    gamemode_change: false
    region_enter: false
    region_exit: false
