# AntiShare Configuration:
# Events:
# 	'block_place' - Blocks/items to deny for block placing
# 	'block_break' - Blocks/items to deny for block breaking
# 	'death' - Blocks/items to not allow to drop on death
# 	'drop_item' - Block/items to not allow to drop when a player presses (default) Q
# 	'interact' - Blocks/items to deny interactions to. (Left/Right click)
#   'commands' - Commands to block, define a new command with a SPACE (defaults block '/spawn' and '/home')
# 	-- Want all blocks/items to be denied? Put a *
# 	-- Want no blocks/items to be denied? Put: none
# 	-- Make sure item lists are space-seperated, not commas, periods, or fancy other things!
# 
# Messages:
# 	All messages are when they are declined an action.
# 	Chat colors are supported using the & sign (eg: &f = white)
#   If you wouldn't like a message to show, set the value as 'noshow'
# 
# Other:
# 	'only_if_creative' - Auto-decline if they are in creative, permissions still apply.
# 		(eg: A player doesn't have the allow or decline permission to place, and is in creative, places a block: declined)
# 	'allow_eggs' - If false then eggs cannot be used (the ones that spawn mobs, like creepers)
# 	'inventory_swap' - If true then creative and survival inventories will be swapped
# 	'track_blocks' - If true then creative mode blocks will be tracked where only creative mode players can break them
#  						(unless they have the permission "AntiShare.blockBypass")	
#   'allow_bedrock' - If false then bedrock will never be broken or placed
#   'pvp' - True if you want to allow creative players to hit other players ("AntiShare.pvp" to allow to specific players)
#   'pvp-mobs' - True if you want to allow creative players to be able to hit mobs ("AntiShare.mobpvp" to allow to specific players)
#   'blockDrops' - Only works if 'track_blocks' is in effect. If true, you allow allow the creative-mode block to be broken, but no drops will be produced
#                  If false, you don't allow the block to be broken (1.0.6 and prior default). While breaking (if this is true) AntiShare sends the message
#                  'noBlockDrop' to the player once per second, or for every different block. As well, when the block is 100% broken it will show 'creativeModeBlock'.
#   'worldTransfer' - True if you would like to allow players to transfer worlds. Suggested value of 'true' is 'only_if_creative' is false
#                     True means you can transfer TO the world, false means you cannot.
#   'tracked-blocks' - The blocks the plugin should track and mark as "creative" blocks (if the player placing is in creative). This list is SPACE defined (see default)
#                    You can set this to 'none' or '*' as well if you prefer, 'none' meaning don't track (set 'track_blocks' to false to reduce some possible lag), '*' meaning
#                    track everything placed.
# 
#   The following are affected by 'only_if_creative': 'allow_eggs', 'allow_bedrock', 'pvp', 'pvp-mobs', 'worldTransfer', and all the 'events'
#   This means the above settings will check if they are in creative or not and act upon that
# SQL:
#   'use' - If this is false, flat-file storage will be used instead
#   'host' - The SQL host, usually localhost
#   'username' - The SQL username to use, this user must be able to create/edit/view tables in the database
#   'password' - The SQL password for the above username
#   'port' - The SQL port, this is unused thus far (will be used in later support)
#   'database' - The SQL database to use, this must already be made
# 
# Notifications: 
#   - Used to alert specific people of actions taking place
#   'illegal' - All the illegal (blocked) actions, the name of the action relates to the action (eg: block_place means an illegal block was placed)
#   'legal' - All the legal (allowed) actions, the name of the action relates to the action (eg: block_place means an legal block was placed)
#   'general' - Everything else that doesn't fit into a category (illegal/legal)
#  
# Permissions:
# 	'AntiShare.*' - Deny all events
# 	'AntiShare.place' - Deny block placing
# 	'AntiShare.break' - Deny block breaking
# 	'AntiShare.death' - Deny item drops on death
# 	'AntiShare.drop' - Deny item dropping
# 	'AntiShare.interact' - Deny interactions
# 	'AntiShare.eggs' - Deny eggs that spawn mobs
#   'AntiShare.commands' - Deny command usage (for specified commands)
# 	-- If you want to allow an event, change the node to 'AntiShare.allow' (eg: 'AntiShare.allow.place' would allow placing)
# 	'AntiShare.reload' - Permission to use /antishare
# 	'AntiShare.noswap' - If true, the player is exempt from inventory swapping, otherwise they will have their inventory switched
# 	'AntiShare.blockBypass' - If true, then the player can bypass the "Creative mode players can only break this block" message
#                           - As well they can break a block and get drops if 'blockDrops' (under 'other') is true
# 	'AntiShare.freePlace' - If true, then the player can place a "creative-mode" block without it being registered as a "creative-mode" block
# 	'AntiShare.bedrock' - If true, then the player can break and place bedrock
#   'AntiShare.pvp' - Allows PVP to a creative mode player
#   'AntiShare.mobpvp' - Allows Mob PVP to a creative mode player
#   'AntiShare.worlds' - Allows world teleporting without being blocked
#   'AntiShare.notify' - Sends notifications to the player
# 	'AntiShare.admin' - Includes "AntiShare.allow.*", "AntiShare.reload", "AntiShare.blockBypass", 
#                         "AntiShare.freePlace", "AntiShare.bedrock", "AntiShare.pvp", "AntiShare.worlds",
#                         "AntiShare.notify", and "AntiShare.mobpvp".
# 
# Commands:
# 	'/antishare' - Reloads configuration
# 		Aliases: '/as', '/antis', '/ashare'
# 
# Notes:
# 	- Permissions default to all deny as true while all allow as OP or higher.
# 	- 'only_if_creative' will override the permissions meaning if a player is in survival-mode while 'only_if_creative' is true then 
# 	  the deny permissions will be ignored (eg: That survival player places a block: it is placed)
# 	- The default settings decline interactions with furnaces, chests, dispensers, and chest-minecarts
# 	- The event 'block_break' is set to 'none' because in creative-mode, no blocks are dropped when broken
#   - Messages support colors, use '&' to define a color. Eg: "&aWelcome!" will display "Welcome!" in green.
events:
  block_break: none
  block_place: 57 41 42
  death: '*'
  drop_item: '*'
  interact: 23 61 62 54 342
  commands: '/spawn /home'
messages:
  block_break: You can't do that!
  block_place: You can't do that!
  death: You can't do that!
  drop_item: You can't do that!
  interact: You can't do that!
  eggs: You can't use the spawn eggs!
  inventory_swap: Your inventory has been changed.
  creativeModeBlock: You cannot break that block! It was placed by a creative mode player.
  bedrock: You cannot play with bedrock!
  pvp: You cannot hit other players!
  mobpvp: You cannot hit mobs!
  noBlockDrop: You will not get anything from breaking that!
  illegalCommand: You cannot use that command!
  worldSwap: You cannot transfer to that world!
other:
  only_if_creative: true
  allow_eggs: false
  inventory_swap: true
  track_blocks: true
  allow_bedrock: false
  pvp: false
  pvp-mobs: false
  blockDrops: false
  worldTransfer: false
  tracked-blocks: '*'
SQL:
  use: false
  host: localhost
  username: AntiShare
  password: AntiSharePW
  port: 3306
  database: AntiShare
notifications:
  illegal:
    block_place: true
    block_break: true
    death: true
    drop_item: true
    interact: true
    command: true
    egg: true
    creative_block_break: true
    pvp: true
    mob-pvp: true
    bedrock_attempt: true
  legal:
    block_place: false
    block_break: false
    death: false
    drop_item: false
    interact: false
    command: false
    egg: false
    creative_block_break: false
    pvp: false
    mob-pvp: false
  general:
    gamemode_change: true
    world_transfer: true
