# For help see the following page
# http://dev.bukkit.org/server-mods/antishare/pages/3-2-x-help/
# 
# Commands Help:
# http://dev.bukkit.org/server-mods/antishare/pages/3-2-x-help/#w-commands
# 
# Permissions Help:
# http://dev.bukkit.org/server-mods/antishare/pages/3-2-x-help/#w-permissions
blocked-actions:
  block-place: true
  block-break: true
  drop-items-on-death: true
  pickup-items: true
  drop-items: true
  right-click: true
  use-items: true
  commands: true
  combat-against-players: true
  combat-against-mobs: true
handled-actions:
  world-transfers: false
  gamemode-inventories: true
enabled-features:
  gamemode-regions: true
  world-split: true
  sql: false
  no-experience-for-creative: true
  no-drops-when-block-break:
    inventories: true
    attached-blocks: true
gamemode-change-cooldown:
  use: false
  time-in-seconds: 5
settings:
  sql:
    host: localhost
    username: MySQLUsername
    password: MySQLPassword
    database: AntiShare
  send-usage-statistics: true
  track-blocks: true
  survival-breaking-creative-blocks:
    block-drops: false
    deny: true
  creative-breaking-survival-blocks:
    block-drops: false
    deny: true
blocked-lists:
  block-place: diamond block, gold block, iron block, bedrock, tnt
  block-break: none
  dropped-items-on-death: all
  picked-up-items: all
  dropped-items: all
  right-click: storage minecart, powered minecart, chest, furnace, dispenser, jukebox
  use-items: fire, flint and steel, exp bottle, 383, egg, lava bucket, water bucket, fireball
  commands: /someCommand, /anotherCommand
worldsplit:
  split: none
  value: 0
  creative: 1
  survival: 0
  warning:
    enabled: false
    blocks: 15
    warn-every: 2
block-tracking:
  tracked-survival-blocks: all
  tracked-creative-blocks: all
other:
  debug: false
  silent-startup: false
  silent-shutdown: false
  silent-blocks: true
  silent-errors: false
  silent-overall: false
  send-gamemode-change-message: true
xMail:
  creative-can-send-items: false
  hook-into-xMail: true